name: GameEvents
version: ${project.version}
main: net.serveron.mcstar.gameevents.GameEvent
api-version: 1.16
commands:
  cg:
    usage: /cg
    description: Custom Game
  td:
    usage: /td
    description: Team Division

permissions:
  cg.*:
    description: Gives access to all commands
    default: op
  td.*:
    description: Gives access to all commands
    default: op